[package]
name = "darling"
version = "0.1.0"
authors = ["Kilerd <blove694@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pilot= "0.0.3"
surf = "2.2.0"
tokio = { version = "1.9.0", features = ["full"] }
