FROM rust as builder
WORKDIR app
COPY . .
# This works with the dummy project generated by `cargo new app --bin`
RUN cargo build --release --bin darling

FROM rust as runtime
WORKDIR app
COPY --from=builder /app/target/release/darling /usr/local/bin
ENV RUST_LOG warn,darling=info
ENV GITHUB_TOKEN MUST_SET
ENV REPO MUST_SET
ENV TELEGRAM_TOKEN MUST_SET
ENV CHAT MUST_SET

ENTRYPOINT ["/usr/local/bin/darling"]